version: '3'
services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - "./prometheus/config:/etc/prometheus"
      - "./prometheus/data:/prometheus"
    networks:
      - monitoring
    ports:
      - 9090:9090
  grafana:
    image: grafana/grafana-enterprise
    container_name: grafana
    restart: unless-stopped
    user: '0'
    networks:
      - monitoring
    ports:
      - '3000:3000'
    volumes:
      - './grafana/data:/var/lib/grafana'
networks:
  monitoring:
    driver: bridge
